### ISSUE TITLE
Assigning instance variable to self

### ISSUE THREAD

**Issue by jvanlint** [keysolutions/cksparkline#4]
I'm getting 2 warnings in the example project and in my own project when I add the the h and m files.

Assigning instance variable to itself on:
 CK_ARC_RELEASE(data);

and on
CK_ARC_RELEASE(computedData);

Any ideas?

Running XCode 4.6.3

**Comment by keysolutions** [comment]
Try pulling the latest version. I have updated it to remove the warning in recent versions of the compiler. Hope this helps.
